# config/paths.yml
project_root: "/g/data/es60/users/thomas_moore/code/ACD/ACD-ARD"
scratch_root: "/scratch/es60/thomas_moore/ACD-ARD"

manifests:    "${project_root}/manifests"
logs:         "${project_root}/logs"
notebooks:    "${project_root}/notebooks"

# Common aliases used by code/tests
base_path:     "${scratch_root}"
base_zarr_path: "${scratch_root}/zarr/base"

zarr_base:     "${scratch_root}/zarr/base"
zarr_ard:      "${scratch_root}/zarr/ard"
rechunk_tmp:   "${scratch_root}/tmp_rechunk"
dask_spill:    "${scratch_root}/dask/worker-spill"