project_root: /scratch/xv83/tm4888/tmp/pytest-of-tm4888/pytest-2/test_smoke0/proj
scratch_root: /scratch/xv83/tm4888/tmp/pytest-of-tm4888/pytest-2/test_smoke0/scratch
manifests: /scratch/xv83/tm4888/tmp/pytest-of-tm4888/pytest-2/test_smoke0/proj/manifests
logs: /scratch/xv83/tm4888/tmp/pytest-of-tm4888/pytest-2/test_smoke0/proj/logs
notebooks: /scratch/xv83/tm4888/tmp/pytest-of-tm4888/pytest-2/test_smoke0/proj/notebooks
zarr_base: /scratch/xv83/tm4888/tmp/pytest-of-tm4888/pytest-2/test_smoke0/scratch/zarr/base
zarr_custom: /scratch/xv83/tm4888/tmp/pytest-of-tm4888/pytest-2/test_smoke0/scratch/zarr/custom
rechunk_tmp: /scratch/xv83/tm4888/tmp/pytest-of-tm4888/pytest-2/test_smoke0/scratch/tmp_rechunk
dask_spill: /scratch/xv83/tm4888/tmp/pytest-of-tm4888/pytest-2/test_smoke0/scratch/dask/worker-spill
