name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install editable package plus developer/test tools from extras
        pip install -e .[dev]
    
    - name: Lint with ruff
      run: |
        ruff check src/ tests/

    - name: Format check (black)
      run: black --check .

    - name: Type check (mypy)
      run: mypy src/

    - name: Tests (minimal smoke)
      run: |
        pytest -q -m "not slow and not hpc" tests/test_min_smoke.py \
          --junitxml=pytest.xml --cov=src --cov-report=xml:coverage.xml

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-artifacts
        path: |
          pytest.xml
          coverage.xml
    
    - name: Test CLI commands
      run: |
        acd-ard manifest --help
        acd-ard base --help
        acd-ard rechunk --help
